In [ ]:
import tensorflow as tf
print("Version of tensorflow is : ",tf.__version__)

In [2]:
@tf.function
def add(x , y):
    return x+y

In [4]:
a = tf.Variable(1.0)
b = tf.Variable(2.0)

print("Add of a & b is : ",add(a , b))

Add of a & b is :  tf.Tensor(3.0, shape=(), dtype=float32)


In [6]:
print("Function is :\n==========================================\n",tf.autograph.to_code(add.python_function))

Function is :
 def tf__add(x, y):
    with ag__.FunctionScope('add', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = (ag__.ld(x) + ag__.ld(y))
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [11]:
@tf.function
def relu(x):
    return tf.where(x < 0 , 0 , x)

In [12]:
print("Relu(5) : ",relu(5))

Relu(5) :  tf.Tensor(5, shape=(), dtype=int32)


In [14]:
print(tf.autograph.to_code(relu.python_function))

def tf__relu(x):
    with ag__.FunctionScope('relu', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = ag__.converted_call(ag__.ld(tf).where, ((ag__.ld(x) < 0), 0, ag__.ld(x)), None, fscope)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [18]:
a = tf.Variable(1.0)
b = tf.Variable(2.0)
@tf.function
def f(x , y):
    a.assign(y * b) # 4
    b.assign_add(x * a) #6
    return a+b
print(f(1.0,2.0))
print(tf.autograph.to_code(f.python_function))

tf.Tensor(10.0, shape=(), dtype=float32)
def tf__f(x, y):
    with ag__.FunctionScope('f', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        ag__.converted_call(ag__.ld(a).assign, ((ag__.ld(y) * ag__.ld(b)),), None, fscope)
        ag__.converted_call(ag__.ld(b).assign_add, ((ag__.ld(x) * ag__.ld(a)),), None, fscope)
        try:
            do_return = True
            retval_ = (ag__.ld(a) + ag__.ld(b))
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [19]:
@tf.function
def sign(a):
    if a>0:
        return "Pos"
    else:
        return "neg"

print(sign(2))
print(sign(-2))

print("Function is :\n=============================================\n\n",tf.autograph.to_code(sign.python_function))

tf.Tensor(b'Pos', shape=(), dtype=string)
tf.Tensor(b'neg', shape=(), dtype=string)
Function is :

 def tf__sign(a):
    with ag__.FunctionScope('sign', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()

        def get_state():
            return (do_return, retval_)

        def set_state(vars_):
            nonlocal do_return, retval_
            (do_return, retval_) = vars_

        def if_body():
            nonlocal do_return, retval_
            try:
                do_return = True
                retval_ = 'Pos'
            except:
                do_return = False
                raise

        def else_body():
            nonlocal do_return, retval_
            try:
                do_return = True
                retval_ = 'neg'
            except:
                do_return = False
                raise
        ag__.i

In [23]:
@tf.function
def f(x):
    while tf.reduce_sum(x) > 1:
        tf.print(x)
        x = tf.tanh(x)
    tf.print("DONE :')")
f(tf.random.uniform(([5])))
print("\n\n\nFunction :\n\n",tf.autograph.to_code(f.python_function))

[0.286578655 0.157721639 0.848540664 0.269229054 0.112782359]
[0.278982759 0.156426683 0.690306365 0.262907296 0.11230658]
[0.271963298 0.155163154 0.598178804 0.257012784 0.111836769]
[0.265450716 0.1539298 0.535752356 0.251499355 0.111372821]
[0.259386659 0.152725443 0.489765912 0.246327549 0.110914595]
[0.253721744 0.151548967 0.454030633 0.241463393 0.110461988]
[0.24841395 0.150399312 0.425206572 0.236877501 0.110014878]
[0.243427172 0.149275452 0.401307583 0.232544243 0.109573156]
[0.238730237 0.148176461 0.381067187 0.228441224 0.109136716]
[0.234296024 0.147101432 0.363633871 0.224548683 0.108705461]
[0.230100885 0.146049485 0.348410845 0.220849171 0.10827928]
[0.226124048 0.145019814 0.334965438 0.217327237 0.107858062]
[0.222347185 0.144011661 0.322975338 0.213969111 0.107441731]
DONE :')



Function :

 def tf__f(x):
    with ag__.FunctionScope('f', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) a